export const smallStats = {
	running: [
		'distance',
		'duration',
		'averageSpeed',
		'elevationGain',
		'averageHR',
	],
	ultra_run: [
		'distance',
		'duration',
		'averageSpeed',
		'elevationGain',
		'averageHR',
	],
	obstacle_run: [
		'distance',
		'duration',
		'averageSpeed',
		'elevationGain',
		'averageHR',
	],
	cycling: [
		'distance',
		'duration',
		'averageSpeed',
		'elevationGain',
		'averagePower',
	],
	swimming: ['distance', 'duration', 'averageSpeed', 'calories', 'averageHR'],
	open_water_swimming: [
		'distance',
		'duration',
		'averageSpeed',
		'calories',
		'averageHR',
	],
	walking: ['distance', 'duration', 'averageSpeed', 'averageHR', 'calories'],
	hiking: ['distance', 'calories', 'duration', 'averageHR', 'averageSpeed'],
	disc_golf: ['distance', 'calories', 'duration', 'averageHR', 'averageSpeed'],
	fitness_equipment: [
		'totalSets',
		'duration',
		'averageHR',
		'maxHR',
		'calories',
	],
	indoor_cardio: ['totalSets', 'duration', 'averageHR', 'maxHR', 'calories'],
	boxing: ['totalSets', 'duration', 'averageHR', 'maxHR', 'calories'],
	mixed_martial_arts: [
		'totalSets',
		'duration',
		'averageHR',
		'maxHR',
		'calories',
	],
	other: ['distance', 'duration', 'averageSpeed', 'averageHR', 'calories'],
	water_sports: [
		'distance',
		'duration',
		'averageSpeed',
		'averageHR',
		'calories',
	],
	kayaking_v2: [
		'distance',
		'duration',
		'averageSpeed',
		'averageHR',
		'calories',
	],
	paddling_v2: [
		'distance',
		'duration',
		'averageSpeed',
		'averageHR',
		'calories',
	],
	stand_up_paddleboarding_v2: [
		'distance',
		'duration',
		'averageSpeed',
		'averageHR',
		'calories',
	],
	rowing_v2: ['distance', 'duration', 'averageSpeed', 'averageHR', 'calories'],
	winter_sports: [
		'distance',
		'duration',
		'averageSpeed',
		'averageHR',
		'calories',
	],
	uncategorized: ['distance', 'calories', 'duration', 'averageHR', 'maxHR'],
	multi_sport: [
		'duration',
		'distance',
		'calories',
		'elevationGain',
		'averageSpeed',
	],
	indoor_climbing: [
		'splitSummaries.noOfSplits.CLIMB_ACTIVE',
		'splitSummaries.maxGradeValue.CLIMB_ACTIVE',
		'splitSummaries.duration.CLIMB_ACTIVE',
		'splitSummaries.totalAscent.CLIMB_ACTIVE',
		'splitSummaries.numClimbSends.CLIMB_ACTIVE',
	],
	bouldering: [
		'splitSummaries.noOfSplits.CLIMB_ACTIVE',
		'splitSummaries.maxGradeValue.CLIMB_ACTIVE',
		'splitSummaries.duration.CLIMB_ACTIVE',
		'calories',
		'averageHR',
	],
	apnea_diving: [
		'maxDepth',
		'bottomTime',
		'numberOfApneaDives',
		'totalSurfaceTime',
		'summarizedDiveInfo.waterType',
	],
	apnea_hunting: [
		'maxDepth',
		'bottomTime',
		'numberOfApneaDives',
		'totalSurfaceTime',
		'summarizedDiveInfo.waterType',
	],
	yoga: ['totalSets', 'duration', 'averageHR', 'maxHR', 'calories'],
	hiit: ['duration', 'averageHR', 'maxHR', 'totalSets', 'calories'],
	motorcycling: [
		'distance',
		'duration',
		'averageSpeed',
		'averageHR',
		'calories',
	],
	diving: [
		'maxDepth',
		'bottomTime',
		'minTemperature',
		'calories',
		'surfaceInterval',
	],
	auto_racing: [
		'bestLapTime',
		'maxSpeed',
		'lapCount',
		'elevationGain',
		'elevationLoss',
	],
	safety: ['duration', 'averageHR', 'distance', 'averageSpeed', 'maxSpeed'],
	resort_skiing_snowboarding_ws: [
		'distance',
		'duration',
		'elevationLoss',
		'maxSpeed',
		'lapCount',
	],
	resort_skiing: [
		'distance',
		'duration',
		'elevationLoss',
		'maxSpeed',
		'lapCount',
	],
	resort_snowboarding: [
		'distance',
		'duration',
		'elevationLoss',
		'maxSpeed',
		'lapCount',
	],
	backcountry_skiing_snowboarding_ws: [
		'distance',
		'duration',
		'elevationGain',
		'elevationLoss',
		'averageHR',
	],
	backcountry_skiing: [
		'distance',
		'duration',
		'elevationGain',
		'elevationLoss',
		'averageHR',
	],
	backcountry_snowboarding: [
		'distance',
		'duration',
		'elevationGain',
		'elevationLoss',
		'averageHR',
	],
	cross_country_skiing_ws: [
		'distance',
		'duration',
		'averageSpeed',
		'averagePower',
		'averageHR',
	],
	skate_skiing_ws: [
		'distance',
		'duration',
		'averageSpeed',
		'averagePower',
		'averageHR',
	],
	breathwork: [
		'duration',
		'averageHR',
		'maxHR',
		'avgRespirationRate',
		'differenceStress',
	],
	meditation: [
		'duration',
		'averageHR',
		'maxHR',
		'avgRespirationRate',
		'differenceStress',
	],
	offshore_grinding: [
		'maxSpeed',
		'duration',
		'averageHR',
		'averagePower',
		'averageBikingCadenceInRevPerMinute',
	],
	offshore_grinding_v2: [
		'maxSpeed',
		'duration',
		'averageHR',
		'averagePower',
		'averageBikingCadenceInRevPerMinute',
	],
	onshore_grinding: [
		'duration',
		'averageHR',
		'averagePower',
		'averageBikingCadenceInRevPerMinute',
		'calories',
	],
	onshore_grinding_v2: [
		'duration',
		'averageHR',
		'averagePower',
		'averageBikingCadenceInRevPerMinute',
		'calories',
	],
	surfing: [
		'splitSummaries.noOfSplits.SURF_ACTIVE',
		'splitSummaries.maxDistance.SURF_ACTIVE',
		'splitSummaries.maxSpeed.SURF_ACTIVE',
		'splitSummaries.duration.SURF_ACTIVE',
		'duration',
	],
	surfing_v2: [
		'splitSummaries.noOfSplits.SURF_ACTIVE',
		'splitSummaries.maxDistance.SURF_ACTIVE',
		'splitSummaries.maxSpeed.SURF_ACTIVE',
		'splitSummaries.duration.SURF_ACTIVE',
		'duration',
	],
	water_tubing: [
		'splitSummaries.noOfSplits.SURF_ACTIVE',
		'splitSummaries.maxDistance.SURF_ACTIVE',
		'splitSummaries.maxSpeed.SURF_ACTIVE',
		'splitSummaries.duration.SURF_ACTIVE',
		'duration',
	],
	wakeboarding: [
		'splitSummaries.noOfSplits.SURF_ACTIVE',
		'splitSummaries.maxDistance.SURF_ACTIVE',
		'splitSummaries.maxSpeed.SURF_ACTIVE',
		'splitSummaries.duration.SURF_ACTIVE',
		'duration',
	],
	wakeboarding_v2: [
		'splitSummaries.noOfSplits.SURF_ACTIVE',
		'splitSummaries.maxDistance.SURF_ACTIVE',
		'splitSummaries.maxSpeed.SURF_ACTIVE',
		'splitSummaries.duration.SURF_ACTIVE',
		'duration',
	],
	wakesurfing: [
		'splitSummaries.noOfSplits.SURF_ACTIVE',
		'splitSummaries.maxDistance.SURF_ACTIVE',
		'splitSummaries.maxSpeed.SURF_ACTIVE',
		'splitSummaries.duration.SURF_ACTIVE',
		'duration',
	],
	waterskiing: [
		'splitSummaries.noOfSplits.SURF_ACTIVE',
		'splitSummaries.maxDistance.SURF_ACTIVE',
		'splitSummaries.maxSpeed.SURF_ACTIVE',
		'splitSummaries.duration.SURF_ACTIVE',
		'duration',
	],
	e_sport: ['duration', 'avgStress', 'averageHR', 'maxStress'],
	windsurfing: [
		'distance',
		'duration',
		'averageSpeed',
		'maxSpeed',
		'averageHR',
	],
	windsurfing_v2: [
		'distance',
		'duration',
		'averageSpeed',
		'maxSpeed',
		'averageHR',
	],
	snorkeling: ['duration', 'averageHR', 'calories', 'distance'],
	wheelchair_push_run: [
		'distance',
		'duration',
		'averageSpeed',
		'elevationGain',
		'averageHR',
	],
	wheelchair_push_walk: [
		'distance',
		'duration',
		'averageSpeed',
		'averageHR',
		'calories',
	],
	para_sports: [
		'distance',
		'duration',
		'averageSpeed',
		'elevationGain',
		'averageHR',
	],
	team_sports: [
		'distance',
		'duration',
		'averageSpeed',
		'averageHR',
		'calories',
	],
	racket_sports: [
		'distance',
		'duration',
		'averageSpeed',
		'averageHR',
		'calories',
	],
	jump_rope: ['totalSets', 'duration', 'averageHR', 'maxHR', 'calories'],
};
