import type { Metadata } from 'next';
import { Inter, Open_Sans, Roboto } from 'next/font/google';
import '../../assets/styles/globals.scss';
import { AuthLayout } from '@/components/layouts/auth-layout/AuthLayout';
import { NotFoundLayout } from '@/components/layouts/not-found-layout/NotFoundLayout';

const roboto = Roboto({
	subsets: ['latin', 'cyrillic'],
	weight: ['100', '300', '400', '500', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="normal">
			<body className={roboto.className}>
				<NotFoundLayout>{children} </NotFoundLayout>
			</body>
		</html>
	);
}
